steps:
  # Build the container image and push it with Kaniko
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --dockerfile=./sdk.Dockerfile
      - --context=.
      - --cache=true
      - --cache-ttl=6h
      - --destination=${_OUTPUT_SDK_IMAGE}
      - --build-arg=SDK_BASE_IMAGE=${_SDK_BASE_IMAGE}