version: "3.9"

services:
  oracle:
    image: qnguyen3496/oracledb:latest
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=${ORACLE_SID}
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_PWD=${ORACLE_PWD}
    volumes:
      - ./data:/opt/oracle/oradata